<center><h1> Série de Travaux Pratiques N° 7 - Machine Learning </h1></center>
<center><h2> K-Nearest Neighbor and Decision Tree</h2></center>

---



Pour ce TP, on utilisera le **dataset IRIS**. Ce dernier est une base de données regroupant les caractéristiques de **trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica**. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 150 observations (50 observations par espèce).

# **Partie I : K-Nearest Neighbor**

# **Questions :**

1- Importer les packages nécessaires

2- Lire l'ensemble de données dans le dataframe pandas

3- Afficher et explorer l'ensemble de données "**iris.csv**"

4- Extraire les variables d'entrée X

5- Extraire les variables de sortie y

6- Diviser le dataset en Train / Test

7- Mise à l'échelle des fonctionnalités avec Transform()

8- Définir votre modèle **KNN**

9- Entraîner le modèle

10- Prédiction sur l'ensemble de test

11- Évaluation du modèle à l'aide de métriques

In [ ]:
# IRIS Dataset : KNN


# 1- Importer les packages nécessaires

# 2- Lire l'ensemble de données dans le dataframe pandas

# 3- Afficher et explorer l'ensemble de données "**iris.csv**"

# 4- Extraire les variables d'entrée X

# 5- Extraire les variables de sortie y

# 6- Diviser le dataset en Train / Test

# 7- Mise à l'échelle des fonctionnalités avec Transform()

# 8- Définir votre modèle KNN

# 9- Entraîner le modèle

# 10- Prédiction sur l'ensemble de test

# 11- Évaluation du modèle à l'aide de métriques

#12- Changer le K = {5, 10, 20, 30, 40}, que remarquez-vous?

In [1]:
import numpy
import pandas
from sklearn.model_selection import train_test_split 

In [2]:
data=pandas.read_csv('iris.csv')
data.head

<bound method NDFrame.head of      sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]>

In [3]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [4]:
X=data[['sepal.length','sepal.width','petal.length','petal.width']]
print(X)

     sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [5]:
y=data[['variety']]
print(y)

       variety
0       Setosa
1       Setosa
2       Setosa
3       Setosa
4       Setosa
..         ...
145  Virginica
146  Virginica
147  Virginica
148  Virginica
149  Virginica

[150 rows x 1 columns]


In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print('tet')

tet


C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
classi=KNeighborsClassifier(n_neighbors=20)

In [11]:
classi.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=20)

In [12]:
ypredict=classi.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, ypredict)
print("Matrice de confusion :\n", conf_matrix)

Matrice de confusion :
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [16]:
accuracy = accuracy_score(y_test, ypredict)
print("Accuracy du modèle :", accuracy)
# le rapport de classification
class_report = classification_report(y_test, ypredict)
print("Rapport de classification :\n", class_report)

Accuracy du modèle : 1.0
Rapport de classification :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# **Partie II : Decision Trees**

# **Questions :**

1- Importer les packages nécessaires

2- Lire l'ensemble de données dans le dataframe pandas

3- Afficher et explorer l'ensemble de données "**iris.csv**"

4- Extraire les variables d'entrée X

5- Extraire les variables de sortie y

6- Diviser le dataset en Train / Test

7- Mise à l'échelle des fonctionnalités avec Transform()

8- Définir votre modèle **Decision Tree**

9- Entraîner le modèle

10- Prédiction sur l'ensemble de test

11- Évaluation du modèle à l'aide de métriques

In [ ]:
# IRIS Dataset : Decision Tree


# 1- Importer les packages nécessaires

# 2- Lire l'ensemble de données dans le dataframe pandas

# 3- Afficher et explorer l'ensemble de données "iris.csv"

# 4- Extraire les variables d'entrée X

# 5- Extraire les variables de sortie y

# 6- Diviser le dataset en Train / Test

# 7- Mise à l'échelle des fonctionnalités avec Transform()

# 8- Définir votre modèle KNN

# 9- Entraîner le modèle

# 10- Prédiction sur l'ensemble de test

# 11- Évaluation du modèle à l'aide de métriques

In [24]:
import numpy
import pandas
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier


In [18]:
data= pandas.read_csv('iris.csv')

In [19]:
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [20]:
X = data.drop(columns='variety')
y = data['variety']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [25]:
tree= DecisionTreeClassifier(random_state=42)

In [26]:
tree.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [31]:
ypredict2=tree.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
conf_matrix = confusion_matrix(y_test, ypredict2)
print("Matrice de confusion :\n", conf_matrix)

Matrice de confusion :
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [33]:
accuracy = accuracy_score(y_test, ypredict2)
print("Accuracy du modèle :", accuracy)
# le rapport de classification
class_report = classification_report(y_test, ypredict2)
print("Rapport de classification :\n", class_report)

Accuracy du modèle : 1.0
Rapport de classification :
               precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        10
  Versicolor       1.00      1.00      1.00         9
   Virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

